export default {
	SUPABASE_REST_API_URL: 'https://nvfxbesbgohafwkbhsvv.supabase.co/rest/v1',
	SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZnhiZXNiZ29oYWZ3a2Joc3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUxNTcwMjcsImV4cCI6MjAzMDczMzAyN30.2VLc7SxL3hYJ_lpO4YnMrvGKViKUIBKdooZLyZ4NL5Q',
}
